SELECT 'CREATE DATABASE dss'
    WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'dss')\gexec

DROP TABLE users;

CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);