
services:
  client:
    build:
      context: ../client
      dockerfile: test.Dockerfile

    ports:
      - 3000:3000
    volumes:
      - ../client:/app/client
    restart: always

  server:
    build:
      context: ../server
      dockerfile: test.Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ../server:/app/server
    depends_on:
      db:
        condition: service_healthy
    environment:
      NODE_ENV: development
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: test
      POSTGRES_DB: dss
      DB_PORT: 5432

  db:
    image: postgres
    restart: always
    user: postgres
    volumes:
      - ../server/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=dss
      - POSTGRES_PASSWORD_FILE=test
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
    db-data:



