services:
  server:
    build:
      context: ../server
      dockerfile: test.Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ../server:/app/server
    depends_on:
      db:
        condition: service_healthy
    secrets:
      - db-password
    environment:
      NODE_ENV: test
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/db-password
      POSTGRES_DB: test
      DB_PORT: 5432

  db:
    image: postgres
    restart: always
    user: postgres
    ports:
      - 5432:5432
    secrets:
      - db-password
    volumes:
      - ../server/database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=test
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
      - JWT_SECRET=HbsuSBeo4JXDHdOUbnaQMf43JYGCuhTC2HwlEqJNkLuYgqUFfka1l6YgoexOQ07O
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db-data:
secrets:
  db-password:
    file: ./password.txt

