name: Test
on:
  pull_request:
  push:
    branches:
      - 'main'
      - '24-create-ci'


jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: .ci/compose.yml
      DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASS: ${{ secrets.DOCKERHUB_TOKEN }}
      JWT_SECRET: 1D20ACC612A20748E89C758929C8D297D1BFC9E2FB0220B5D87E6FE2F0659AF7

    steps:
      - name: Test ENV
        run: echo ${{ secrets.DOCKER_USERNAME }}
        
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: Build docker images
        run: docker-compose build

      - name: NPM Install
        run: npm --prefix ./server/ install
        
      - name: Run backend tests
        run: docker-compose run server




